### PR TITLE
Added RowFilter support to enable easier scans for specific group of rows

### PR DESCRIPTION
**Pull request by misterdai**
Haven't managed to run the tests but have added a test for the RowFilter anyway.  Please could someone double check the test runs correctly before accepting this pull request.

Cheers :)

### CODE REVIEW

**Comment by misterdai** [comment]
Just spotted that I missed the Java byte fixture, will add ;)

**Comment by misterdai** [comment]
Any chance this can be added yet?

**Comment by fengmk2** [comment]
Sure!
+1

**Comment by fengmk2** [comment]
@misterdai hbase-client@1.4.0

Thanks!

**Pull request merged**
