### PR TITLE
Use push to add item to array

### PR DESCRIPTION
**Pull request by wision**
Use .push() instead of .add()

### CODE REVIEW

**Comment by fengmk2** [comment]
...

+1

**Comment by fengmk2** [comment]
Why travis ci fail?

**Comment by wision** [comment]
no idea.. didn't have time to check it yet.. but i will post fix soon, so just wait for it:)

**Comment by wision** [comment]
fixed.. we need to automate this a bit

**Comment by fengmk2** [comment]
:100:

**Comment by fengmk2** [comment]
Release 1.2.2

**Pull request merged**
